### ISSUE TITLE
Descrizione generale del progetto

### ISSUE THREAD

**Issue by Wabri** [TantoPer/MoveTheCircle#1]
Questo progetto è un allenamento che ci consentirà di capire come: organizzarci internamente, assegnare i compiti e gestire un vero e proprio progetto. Un piccolo passo per comprendere il mondo dello sviluppo software in team.

Il "giochino" è molto basilare, cliccare su un cerchio per farlo spostare. Per fare un esempio:
O - X
click su O
X - O
Ovviamente tutto ciò deve essere grafico.

Anche se il progetto è semplice dovremmo cercare di coprire tutti gli aspetti:

1. giocatore/i
2. game master
3. interfaccia grafica

Il progetto deve essere sviluppato in linguaggio Java (per una questione di praticità di conoscienze), in particolare sarà necessario utilizzare una libreria esterna per la creazione dell'interfaccia:

1. [swing](https://en.wikipedia.org/wiki/Java_Swing)
2. [swt](https://en.wikipedia.org/wiki/Standard_Widget_Toolkit)
3. [awt](https://en.wikipedia.org/wiki/Java_AWT)

Per la parte del game master e giocatore credo che non sarà necessario l'uso di librerie esterne (almeno per i requisiti attuali).

**Comment by Wabri** [comment]
@DanerSound

**Comment by Wabri** [comment]
comincia a creare la struttura dell'interfaccia grafica, prova a creare una finestra con dei riquadri dentro e prova a metterci una forma all'interno di un riquadro

**Comment by DanerSound** [comment]
<3
